url: "https://luhighperformancecomputingclub.github.io/hpc-website/" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /posts/:title # used to set the url of each post to a title instead of a date
title: "LU High Performance Computing Club" # the name of your site, e.g. ACME Corp.
highlighter: "rouge"